export const classes = [
    {
        label:"其他",
        value:"0"
    },
    {

        label:"电子元件",
        value:"1",
        children:[
            {
                label:"其他",
                value:"0"
            },
            {
                label:"电容",
                value:"1"
            },
            {
                label:"电阻",
                value:"2"
            }
        ]
    },
    {
        label:"线材",
        value:"2",
        children:[
            {
                label:"其他",
                value:"0"
            },
            {
                label:"仪器信号线",
                value:"1"
            },
            {
                label:"电源线",
                value:"2"
            },
            {
                label:"usb-typec",
                value:"3"
            },
            {
                label:"杜邦线",
                value:"4"
            }
        ]
    },
    {
        label:"仪器",
        value:"3",
        children:[
            {
                label:"其他",
                value:"0"
            },
            {
                label:"万用表",
                value:"1"
            },
            {
                label:"信号发生器",
                value:"2"
            },
            {
                label:"示波器",
                value:"3"
            }
        ]
        
    }
]